apiVersion: v1
kind: Namespace
metadata:
  name: rook
---
apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook-eval
  namespace: rook
spec:
  versionTag: master
  dataDirHostPath: /var/lib/rook
  hostNetwork: false
  storage:
    useAllNodes: false
    useAllDevices: true
    deviceFilter: nvm
    metadataDevice:
    location:
    storeConfig:
      storeType: bluestore
      databaseSizeMB: 1024
      journalSizeMB: 1024
    nodes:
    - name: n1
    - name: n2
