---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rookeval-claim
  labels:
    app: eval
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 320Gi
---
kind: Service
apiVersion: v1
metadata:
  name: eval
spec:
  selector:
    app: eval
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rookeval
  labels:
    app: eval
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eval
    spec:
      nodeSelector:
        kubernetes.io/hostname: rook-worker-01
      containers:
      - image: ubuntu
        name: rookeval
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
        - name: eval-block-storage
          mountPath: /eval
      volumes:
      - name: eval-block-storage
        persistentVolumeClaim:
          claimName: rookeval-claim
